# Generated by Django 4.1.7 on 2023-05-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_user_date_of_birth_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
